# Generated by Django 3.2.6 on 2021-08-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
